In [10]:
from geopy.geocoders import Nominatim
from api_keys import api_key
import pandas as pd 

geolocator = Nominatim(user_agent=api_key)
location = geolocator.geocode("175 5th Avenue NYC")
print((location.latitude, location.longitude))

df = pd.read_csv("PIDX_Terminal_Codes.csv")

(40.741059199999995, -73.98964162240998)


In [2]:
df = df[:636]
df.tail()

Submitter            Terminal Owner Name TERMINAL ID  \
631            Shell                         NuStar   TGB000037   
632            Shell  Hertfordshire Oil Storage Ltd   TGB000038   
633            Shell                 Puma Energy UK   TGB000039   
634            Shell                         Valero   TGB000040   
635  Circle K Europe                Circle K Europe   TGB000041   

                                Address TERMINAL CITY/TOWN/LOCALITY  \
631           Eastham, Bankfields Drive                      Wirral   
632                          Green Lane             Hemel Hempstead   
633                           PO Box 10               Milford Haven   
634  Holesmouth Road, Royal Edward Dock                   Avonmouth   
635                        Airport Road                    Sydenham   

    TERMINAL COUNTY/PROVINCE TERMINAL POSTAL CODE TERMINAL COUNTRY  \
631                Liverpool              L62 0BA   United Kingdom   
632            Hertfordshire              HP2 7HZ   United Kingdom   
633            Pembrokeshire             SA73 3FB   United Kingdom   
634                  Bristol             BS11 9BT   United Kingdom   
635                  Belfast              BT3 9DY   United Kingdom   

     TERMINAL GEO COORDINATES  
631                       NaN  
632                       NaN  
633                       NaN  
634                       NaN  
635                       NaN

In [3]:
for index, row in df.iterrows():
    if pd.isnull(row['TERMINAL CITY/TOWN/LOCALITY']) == True:
        print(index)

245


In [11]:
geolocator.geocode("Hamburg, Germany").latitude

53.5437641

In [7]:
df.drop(index=245, inplace=True)
df.reset_index(inplace=True)

In [14]:
lat_list = []
long_list = []
for index, row in df.iterrows():
    try:
        
        location = geolocator.geocode(f"{row['TERMINAL CITY/TOWN/LOCALITY']}, {row['TERMINAL COUNTRY']}")
        lat = location.latitude
        long = location.longitude
        lat_list.append(lat)
        long_list.append(long)
    except AttributeError:
        print(f"Problem index: {index}. Here's more: {row['TERMINAL CITY/TOWN/LOCALITY']}, {row['TERMINAL COUNTRY']}")  

Problem index: 51. Here's more: PORTHARDY, Canada
Problem index: 59. Here's more: SAULTSTEMARIE, Canada
Problem index: 60. Here's more: SAULTSTEMARIE, Canada
Problem index: 66. Here's more: PORTMOODY, Canada
Problem index: 189. Here's more: ANNECY GPHS, France
Problem index: 193. Here's more: CHALON MARNE SFDM, France
Problem index: 203. Here's more: PORT LA NOUV SARAM, France
Problem index: 204. Here's more: PUGET GPCA, France
Problem index: 208. Here's more: SAINT POL DPC, France
Problem index: 209. Here's more: ST JEAN DE BRAYE RM, France
Problem index: 210. Here's more: ST P DES CORPS GSPC , France
Problem index: 211. Here's more: STOCKBREST, France
Problem index: 227. Here's more: LYON DP PORT HERRIOT, France
Problem index: 228. Here's more: GRANDPUITS DIS, France
Problem index: 229. Here's more: GRIGNY CIM, France
Problem index: 230. Here's more: PALLICE PICOTY, France
Problem index: 293. Here's more: Osnabruk, Germany
Problem index: 306. Here's more: Wursburg, Germany


GeocoderTimedOut: Service timed out

In [16]:
len(lat_list)

329

Problem index: 51. Here's more: PORTHARDY, Canada <br>
Problem index: 59. Here's more: SAULTSTEMARIE, Canada <br>
Problem index: 60. Here's more: SAULTSTEMARIE, Canada <br>
Problem index: 66. Here's more: PORTMOODY, Canada <br>
Problem index: 189. Here's more: ANNECY GPHS, France <br>
Problem index: 193. Here's more: CHALON MARNE SFDM, France <br>
Problem index: 203. Here's more: PORT LA NOUV SARAM, France <br>
Problem index: 204. Here's more: PUGET GPCA, France <br>
Problem index: 208. Here's more: SAINT POL DPC, France <br>
Problem index: 209. Here's more: ST JEAN DE BRAYE RM, France
Problem index: 210. Here's more: ST P DES CORPS GSPC , France
Problem index: 211. Here's more: STOCKBREST, France
Problem index: 227. Here's more: LYON DP PORT HERRIOT, France
Problem index: 228. Here's more: GRANDPUITS DIS, France
Problem index: 229. Here's more: GRIGNY CIM, France
Problem index: 230. Here's more: PALLICE PICOTY, France
Problem index: 293. Here's more: Osnabruk, Germany
Problem index: 306. Here's more: Wursburg, Germany

In [17]:
llist = [51, 59, 60, 66, 189, 193, 203, 204, 208, 209, 210, 211, 227, 228, 229, 230, 293, 306]

In [19]:
for i in llist:
    df.drop(index=i, inplace=True)

In [20]:
df.reset_index(inplace=True)

In [28]:
len(df[0:329]) == len(long_list)
df = df[0:329]

In [29]:
df['lat'] = lat_list 
df['long'] = long_list

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [30]:
df

index Submitter                 Terminal Owner Name TERMINAL ID  \
0        0     Shell             BotanyBay B Vopak depot   TAU000001   
1        1     Shell  Botn Vopak BitDepot                  TAU000002   
2        2     Shell                Kwinana Coogee depot   TAU000003   
3        3     Shell          Hobart Caltex depot          TAU000004   
4        4     Shell              DarwinEArm Vopak depot   TAU000005   
..     ...       ...                                 ...         ...   
324    342       DTN                           Jones Oil   TIE000024   
325    343       DTN                           Jones Oil   TIE000025   
326    344       DTN                           Jones Oil   TIE000026   
327    345       DTN                           Jones Oil   TIE000027   
328    346       DTN                           Jones Oil   TIE000028   

                            Address TERMINAL CITY/TOWN/LOCALITY  \
0    49 Friendship Road               Port Botany                 
1    Unwin Street                       Granville                 
2    Patterson Road                   Kwinana                     
3                  Selfs Point Road                    New Town   
4                 780 Berrimah Road   East Arm                    
..                              ...                         ...   
324                    Manor Street                   Waterford   
325                      Prior Park                     Clonmel   
326                  Finisklin Road                       Sligo   
327                             NaN                   Edenderry   
328                             NaN                        Birr   

    TERMINAL COUNTY/PROVINCE TERMINAL POSTAL CODE TERMINAL COUNTRY  \
0                        NaN                 2036        Australia   
1                        NaN                 2142        Australia   
2                        NaN                 6167        Australia   
3                        NaN                 7008        Australia   
4                        NaN                  828        Australia   
..                       ...                  ...              ...   
324                      NaN                  NaN          Ireland   
325                      NaN                  NaN          Ireland   
326                      NaN                  NaN          Ireland   
327                      NaN                  NaN          Ireland   
328                      NaN                  NaN          Ireland   

     TERMINAL GEO COORDINATES        lat        long  
0                         NaN -33.973468  151.217852  
1                         NaN -33.834510  151.006011  
2                         NaN -32.248889  115.843950  
3                         NaN -42.858801  147.305875  
4                         NaN -12.477441  130.901511  
..                        ...        ...         ...  
324                       NaN  52.261000   -7.111908  
325                       NaN  52.355000   -7.703889  
326                       NaN  54.192986   -8.730543  
327                       NaN  53.343366   -7.048858  
328                       NaN  53.096584   -7.910874  

[329 rows x 12 columns]

In [32]:
df.to_excel("lat_long.xlsx")